### ISSUE TITLE
Any way to use this with wrapped node module calls?

### ISSUE THREAD

**Issue by marcsyp** [willhoag/bucket-queue#1]
Hi -- 

This utility looks really useful.  That said, I'm not writing the REST calls myself, I'm using a node wrapper for Shopify.  Is there any way to use this library with the node implementation of a library?

Thanks,
Marc

**Comment by willhoag** [comment]
Hi Marc,

Yeah, so it makes no assumptions on how you use it other than the function must return a promise.

Each addition just takes a `promise returning function` and then `it's arguments` as an array or single value.

Example:
```js
q.add(library.method, [arg1, arg2])

// optionally bind method if it uses a local "this"
q.add(library.method.bind(library), [arg1, arg2])
```

**Comment by marcsyp** [comment]
Awesome -- thanks for the tips.  I will definitely be trying this out with some utility methods in a Shopify node application.

Do you happen to know if your implementation matches the Shopify leaky bucket implementation in terms of settings (I know they say they use a slightly different algo than usual)?  Or do you have some recommended settings for 'q' to work well with Shopify's rate limit policy?

Thanks!

**Comment by willhoag** [comment]
The queue limits the calls for any [`perInterval`](https://github.com/willhoag/bucket-queue#options) window. If it maxes out, it basically pauses until that [`perIterval`](https://github.com/willhoag/bucket-queue#options) window finishes.

So, it's somewhat basic in that it's not "aggressive" calling as often as possible.

In any case, for a Standard Shopify plan:
- bucket size: 40 calls
- leak rate: 2 calls per second

So, bucket is empty after 20 seconds

```js
q = BucketQueue({
  calls: 40,
  perInterval: 20 * 1000, // 20 seconds
}).start()
```

And just in case, you could make the `calls` param less than 40 to be sure to stay under the limit.

Or, as a safety measure, you could catch all responses with a 429 status code and just add them back onto the queue.

```js
// psudo code
q.add(request, url).then(res => {
    if (res.status === 429) {
        q.add(request, url)
        return
    }
}
```
